### ISSUE TITLE
Not working starting from Filament v2.15.29

### ISSUE THREAD

**Issue by mahfoudfx** [pxlrbt/filament-spotlight#10]
Hello,
I noticed some slowness in panel after an update of filament to v2.15.33 than usual, than I found that the plugin is not working at all.
After some inspection, I confirmed that is not working starting from the Filament v2.15.29 (with Laravel 9.26.1/PHP8.1).
I didn't dig deeper, I'm not sure, but I remember that the PR [#3719](https://github.com/filamentphp/filament/pull/3719) regarding support for Turbo Navigation got my attention that may cause similar issues.

**Comment by pxlrbt** [comment]
Is this still valid with the latest version? I accidentally removed the JS file with v0.3.4.
For me, everything is working fine.

**Comment by mahfoudfx** [comment]
Sorry, I didn't noticed that the plugin were update to v0.3.4, that's why I suspected the Filament update.
Now it is OK, I confirm that the plugin is working correctly.
