### ISSUE TITLE
Missing spotlight.js in release v0.3.4

### ISSUE THREAD

**Issue by dmandrade** [pxlrbt/filament-spotlight#11]
The dist spotlight.js file was deleted in the commit [50f8a79](https://github.com/pxlrbt/filament-spotlight/commit/50f8a7973cf8cfc2b430df4ed2564267c51aea3e) and with that the plugin stopped working in version 0.3.4.

**Comment by pxlrbt** [comment]
Sorry, somehow ignored that file from Git. No idea what happened. Should be fixed with the new version
