### ISSUE TITLE
Missing required parameter for [Route: filament.pages.companies/{company}] [URI: companies/{company}] [Missing parameter: company].

### ISSUE THREAD

**Issue by mahavishnup** [pxlrbt/filament-spotlight#17]
Path: `src/Actions/RegisterPages.php`

`$url = $page::getUrl(); `

replace to 

`if (in_array($page, ['Wallo\FilamentCompanies\Pages\Companies\CompanySettings'], true) && FilamentCompanies::hasCompanyFeatures()) {
                $url = $page::getUrl([Auth::user()?->currentCompany]);
            } else {
                $url = $page::getUrl();
            }`

**Comment by grafst** [comment]
but what happens if someone doesn't use FilamentCompanies?
