### ISSUE TITLE
Not enough contrast in dark mode

### ISSUE THREAD

**Issue by grafst** [pxlrbt/filament-spotlight#23]
See this screenshot:
<img width="912" alt="2023-06-13_12-16-21" src="https://github.com/pxlrbt/filament-spotlight/assets/8471055/8f1454f3-c676-4226-88c0-9e03824c7f46">

Fantastic plugin btw! 👍

**Comment by pxlrbt** [comment]
Yeah, I know this is an issue, but I just use the styles of the underlying `LivewireUI/modals` package 😅

**Comment by grafst** [comment]
Ah, so its a filament issue then?

**Comment by pxlrbt** [comment]
No. I just don't apply any styling myself. It's the original styling of https://github.com/wire-elements/spotlight. That's why there is no optimised dark mode style.

**Comment by grafst** [comment]
Ah, ok.
I also wouldn't even know how to improve it, just that like this its almost invisible....
Since its dark in the light mode should it be light in dark mode? 😄
