### ISSUE TITLE
Support for Filament v3

### ISSUE THREAD

**Issue by mokhosh** [pxlrbt/filament-spotlight#27]
```
  Problem 1
    - pxlrbt/filament-spotlight[0.1.0, ..., v0.3.2] require filament/filament ^2.10.34 -> found filament/filament[v2.10.34, ..., v2.17.51] but it conflicts with your root composer.json require (^3.0).
    - pxlrbt/filament-spotlight[v0.3.3, ..., v0.3.8] require filament/filament ^2.14.0 -> found filament/filament[v2.14.0, ..., v2.17.51] but it conflicts with your root composer.json require (^3.0).
    - Root composer.json requires pxlrbt/filament-spotlight * -> satisfiable by pxlrbt/filament-spotlight[0.1.0, ..., v0.3.8].
```

**Comment by pxlrbt** [comment]
PRs are welcome. Otherwise I have to look into it after v3 launch.

**Comment by pxlrbt** [comment]
`wire-modals/spotlight` doesn't support LW v3 yet, but Philo is working on it: https://github.com/wire-elements/spotlight/issues/120

**Comment by aymanalhattami** [comment]
+1

**Comment by pxlrbt** [comment]
@aymanalhattami Please don't "+1". You can +1 via the emoji on the original post. Otherwise this will notify everyone subscribed to this issue. If you read my last comment, you'd see that this is blocked by the dependency not supporting Livewire v3 yet.

**Comment by pxlrbt** [comment]
v3 support merge with #28
