### ISSUE TITLE
Missing translation keys

### ISSUE THREAD

**Issue by digitall-it** [pxlrbt/filament-spotlight#35]
It seems like the english translation is missing some translations, like Search for a :record, Logout, Dashboard and so on. Also, adding 'Search for a :record' as a key in the translation doesn't seem to pick it up here:

`SpotlightCommandDependency::make('record')->setPlaceholder(__('Search for a :record', ['record' => $this->resource::getModelLabel()]))`

I tried to clear the cache, and change both English and Italian languages to this:

<?php

return [
    'placeholder' => 'What do you want to do?',
    'Search for a :record' => 'Test :record',
];

but with no avail.

**Comment by pxlrbt** [comment]
I think the issue here is that the plugin initializes before the Translator is ready and therefore is always shows the english version. I need to look into this.

**Comment by digitall-it** [comment]
I seem to remember that it wasn’t the case, in another project (I don’t remember what it was) I was able to find the correct key. Also the “placeholder” key works. This may be the occasion to search and refactor the translation keys to not use the default translations anymore, so that it becomes evident from the English translation what key to use (if it is possible).
