### ISSUE TITLE
pxlrbt\FilamentSpotlight\Actions\RegisterUserMenu::getUrl(): Return value must be of type string, null returned

### ISSUE THREAD

**Issue by grafidev** [pxlrbt/filament-spotlight#38]
pxlrbt\FilamentSpotlight\Actions\RegisterUserMenu::getUrl(): Return value must be of type string, null returned

**Comment by melvinmihaylovnulabg** [comment]
Hello, i have the same issue and i am with the latest version of the plugin. Do i need to install another version or what?

**Comment by jacquestrdx123** [comment]
Same issue, not sure how to move forward

**Comment by jacquestrdx123** [comment]
Btw, my issue I found the cause by going into the vendor file RegisterUserMenu.php and adding a try catch TypeError, then I was able to find the menu item causing the plugin to crash


public static function boot(Panel $panel)
    {
        $self = new static;
        /**
         * @var array<MenuItem> $items
         */
        $items = $panel->getUserMenuItems();

        foreach ($items as $key => $item) {
            $name = $self->getName($key, $item);
            try{
                $url = $self->getUrl($key, $item);
            }catch (\TypeError $e){
                dd($item);
                $url = '';
            }

**Comment by pxlrbt** [comment]
> then I was able to find the menu item causing the plugin to crash

Is it a default one and a use case that should be supported? We could probably filter out results with an empty url
