### ISSUE TITLE
Add usage details to documentation

### ISSUE THREAD

**Issue by nicollassilva** [pxlrbt/filament-spotlight#4]
The documentation could have some implementation details, such as selecting specific database columns to display a result from a resource, and others we don't know.

**Comment by pxlrbt** [comment]
@underdpt You can. It's using the global search data. I will update the readme after my vacation.

**Comment by grafst** [comment]
> @underdpt You can. It's using the global search data. I will update the readme after my vacation.

it's fantastic that it uses the filament search configuration and doesn't reinvent the wheel! 😄
