### ISSUE TITLE
When using __construct at list page for resources, appear error: Too few arguments to function 

### ISSUE THREAD

**Issue by kamaludin21** [pxlrbt/filament-spotlight#46]
Too few arguments to function App\Filament\Resources\[ResourcesName]\Pages\ListData::__construct(), 0 passed in /Users/zyel/Herd/project-name/vendor/pxlrbt/filament-spotlight/src/Commands/ResourceCommand.php on line 40 and exactly 1 expected

**Comment by pxlrbt** [comment]
You can exclude that page via `shouldRegisterSpotlight()` ( as Spotlight doesn't know what arguments it requires. 

https://github.com/pxlrbt/filament-spotlight?tab=readme-ov-file#excluding-pages

**Comment by kamaludin21** [comment]
> You can exclude that page via `shouldRegisterSpotlight()` ( as Spotlight doesn't know what arguments it requires.
> 
> https://github.com/pxlrbt/filament-spotlight?tab=readme-ov-file#excluding-pages

Thank's, already have in docs, sorry 😅😅
