### ISSUE TITLE
 [Issue] Class "App\Providers\Filament\SpotlightPlugin" not found?

### ISSUE THREAD

**Issue by iamdadmin** [pxlrbt/filament-spotlight#51]
I might've just done something wrong but I followed the installation instructions, added it to the panel plugins, and got this:

![image](https://github.com/user-attachments/assets/2d5cba97-94af-4f35-bb31-be5c4e3be6cc)

**Comment by iamdadmin** [comment]
Okay so I missed out putting the 'use' statement. This is a PEBKAC. Nothing to see here.

**Comment by pxlrbt** [comment]
Usually any IDE should catch this or prompt you to import the class 😅

**Comment by iamdadmin** [comment]
Yeah my linter actually REMOVED the use line a bit aggressively which is why I THOUGHT I'd followed the instructions but it still went wrong! I yeeted the linter... all good now. Sorry :D
